#!/bin/sh

DOTFILES_PATH="~/.dotfiles"

if [ ! -e ~/.oh-my-zsh ]; then
  echo 'Installing/updating oh-my-zsh...'

  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

echo 'Symlinking custom zsh theme...'

ln -sf ~/.dotfiles/zsh/dbiddy.zsh-theme ~/.oh-my-zsh/custom/dbiddy.zsh-theme

echo 'Symlinking zshrc...'

ln -sf ~/.dotfiles/zsh/zshrc ~/.zshrc

echo 'Symlinking aliases...'

ln -sf ~/.dotfiles/aliases ~/.aliases

echo "That's all for now!"
