# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="dbiddy"
#ZSH_THEME="michelebologna"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
if [ -e ~/.aliases ]; then
  source ~/.aliases
fi

if [ -e ~/.aliases.private ]; then
  source ~/.aliases.private
fi

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# plugins=(git heroku rbenv dotenv kubectl kubectl-prompt)
plugins=(git heroku rbenv dotenv kubectl-prompt)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH="/home/dave/bin:/snap/bin:/home/dave/.cargo/bin:/home/dave/apps/android-sdk-linux/tools:/home/dave/apps/android-sdk-linux/platform-tools:/opt/wine-staging/bin:$PATH"

export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin

export ANDROID_HOME=/home/dave/apps/android-sdk-linux

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:/home/dave/apps:$PATH"

export NODE_VIRTUAL_ENV_DISABLE_PROMPT=1
. ~/.node-8.11.3/bin/activate
export VIRTUAL_ENV_DISABLE_PROMPT=1
# . ~/.python-2.7.14/bin/activate

if [ -e ~/.zshrc.private ]; then
  # Stuff that shouldn't go in source control
  . ~/.zshrc.private
fi

setopt HIST_IGNORE_SPACE

export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$HOME/.local/bin
if [[ "$SSH_CONNECTION" != "" ]];then
  if [[ "$SSH_AUTH_SOCK" = "" ]]; then
    ssh-agent /bin/zsh
  fi

  if [[ "$TMUX" = "" ]]; then
    tmux new -s remote || tmux attach -t remote
  fi
fi

export VASSAL_MODULES="${HOME}/vassal/modules"
alias vassal='docker run -d --rm --name vassal -e DISPLAY -v $XAUTHORITY:/root/.Xauthority --net=host --ipc=host --security-opt=no-new-privileges -v ${VASSAL_MODULES}:/root/modules -v $HOME/.VASSAL:/root/.VASSAL mablanco/vassal'
